# Generated by Django 3.2.5 on 2021-07-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter the date in the form of yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Enter the date in the form of yyyy-mm-dd', null=True, verbose_name='Died'),
        ),
    ]
