# Generated by Django 3.2.5 on 2021-07-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210706_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Enter the date in the form of yyyy-mm-dd', null=True),
        ),
    ]
